"""add_user_usage_quotas

Revision ID: 80136f43c9ac
Revises: e5f7c59d8dd4
Create Date: 2026-03-18 04:24:30.653462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80136f43c9ac'
down_revision: Union[str, None] = 'e5f7c59d8dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Update users table first so user_id exists for the foreign key
    op.add_column('projects', sa.Column('project_name', sa.String(), nullable=True))
    op.execute("UPDATE projects SET project_name = 'Project ' || project_id WHERE project_name IS NULL")
    op.alter_column('projects', 'project_name', nullable=False)
    op.create_unique_constraint(None, 'projects', ['project_name'])
    op.execute("ALTER TABLE users ADD COLUMN user_id SERIAL")
    op.add_column('users', sa.Column('user_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('users', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['user_uuid'])
    op.drop_column('users', 'id')
    op.drop_column('users', 'created_at')
    op.create_primary_key('pk_users', 'users', ['user_id'])

    # 2. Now create user_usage_quotas
    op.create_table('user_usage_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('query_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scrape_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_usage_date')
    )
    op.create_index(op.f('ix_user_usage_quotas_id'), 'user_usage_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_user_usage_quotas_user_id'), 'user_usage_quotas', ['user_id'], unique=False)
    op.drop_table('collection_384_70')
    op.drop_table('collection_384_62')
    op.drop_index('collection_384_61_vector_idx', table_name='collection_384_61', postgresql_using='hnsw')
    op.drop_table('collection_384_61')
    op.drop_table('collection_384_68')
    op.drop_table('collection_384_72')
    op.drop_table('collection_384_64')
    op.drop_table('collection_384_69')
    op.drop_index('collection_384_67_vector_idx', table_name='collection_384_67', postgresql_using='hnsw')
    op.drop_table('collection_384_67')
    op.drop_table('collection_384_71')
    op.drop_index('collection_384_65_vector_idx', table_name='collection_384_65', postgresql_using='hnsw')
    op.drop_table('collection_384_65')
    op.drop_table('collection_384_66')
    op.drop_table('collection_384_63')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    op.drop_column('users', 'user_uuid')
    op.drop_column('users', 'user_id')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'project_name')
    op.create_table('collection_384_63',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_63_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_63_pkey')
    )
    op.create_table('collection_384_66',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_66_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_66_pkey')
    )
    op.create_table('collection_384_65',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_65_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_65_pkey')
    )
    op.create_index('collection_384_65_vector_idx', 'collection_384_65', ['vectors'], unique=False, postgresql_using='hnsw')
    op.create_table('collection_384_71',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_71_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_71_pkey')
    )
    op.create_table('collection_384_67',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_67_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_67_pkey')
    )
    op.create_index('collection_384_67_vector_idx', 'collection_384_67', ['vectors'], unique=False, postgresql_using='hnsw')
    op.create_table('collection_384_69',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_69_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_69_pkey')
    )
    op.create_table('collection_384_64',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_64_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_64_pkey')
    )
    op.create_table('collection_384_72',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_72_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_72_pkey')
    )
    op.create_table('collection_384_68',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_68_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_68_pkey')
    )
    op.create_table('collection_384_61',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_61_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_61_pkey')
    )
    op.create_index('collection_384_61_vector_idx', 'collection_384_61', ['vectors'], unique=False, postgresql_using='hnsw')
    op.create_table('collection_384_62',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_62_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_62_pkey')
    )
    op.create_table('collection_384_70',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vectors', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_70_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_70_pkey')
    )
    op.drop_index(op.f('ix_user_usage_quotas_user_id'), table_name='user_usage_quotas')
    op.drop_index(op.f('ix_user_usage_quotas_id'), table_name='user_usage_quotas')
    op.drop_table('user_usage_quotas')
    # ### end Alembic commands ###
